name: Built Assets

on:
  pull_request:
  push:
    branches:
      - built-assets
      - production

jobs:
  built-branch:
    uses: alleyinteractive/.github/.github/workflows/built-assets.yml@built-assets
    with:
      branch: ${{ github.event.pull_request.head.ref || github.ref }}
      node: 16
