name: Create a -built branch

on:
  push:
    branches:
      - main
      - production
      - develop

jobs:
  built-branch:
    uses: alleyinteractive/.github/.github/workflows/built-branch.yml@main
