name: Code Quality

on:
  pull_request:
    branches:
      - production
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '30 8 * * 0' # Run once per week at 8:30am UTC on Sundays.

jobs:
  code-quality:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/php-code-quality.yml@main
    with:
      php: '8.2'
