name: Node Tests

on:
  pull_request:
    branches:
      - production
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '15 8 * * 0' # Run once per week at 8:15am UTC on Sundays.

jobs:
  node-tests:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      ci: true
      node: 18
      run-audit: true
