name: Testing Suite

on:
  pull_request:

jobs:
  unit-tests:
    strategy:
      matrix:
        php: [8.1, 8.2]
        wordpress: [5.9, "latest"]
    uses: alleyinteractive/.github/.github/workflows/php-tests.yml@main
    with:
      php: ${{ matrix.php }}
      wordpress: ${{ matrix.wordpress }}
